import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {  //!
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: "Next.js Team", url: "https://nextjs.org" }],
  keywords: "nextjs, react, blog",
//   "nextjs, react, blog"
//    <meta name="keywords" content="nextjs, react, blog" /> //* se traduce en esto

// ["react", "server components"]
// <meta name="keywords" content="react, server components" />
};

function CommentsPage() {
  return (
    <div>CommentsPage</div>
  )
}

export default CommentsPage

//! Metadata
// al igual que hacíamos con RootLayout, podemos importar el compoennte Matadata y definir las características de dicha página
// si pulsamos CNTRL + click en Metada nos lleva a la página de información del componente
// en el podemos ver todas las características y propiedades del compoennte