import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

//! layout
// un layout es un diseño que se comparte entre varias páginas
// Durante la navegación, los diseños conservan el estado, siguen siendo interactivos y no se vuelven a re-renderizar

//! RootLayout
// como es el primer layout que se encuentra en toda la app, se le nombra RootLayout para saber que es la principal
// El diseño raíz es obligatorio y //* debe contener etiquetas htmly .body
